# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    tags:
      - 'v**'

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install MAUI Workloads
      run: dotnet workload install maui --ignore-failed-sources

    - name: Semver Parse
      id: version
      uses: release-kit/semver@v1.0.10

    - name: Build MauiKeyboardEffects
      run: dotnet build MauiKeyboardEffects/MauiKeyboardEffects.csproj
    - name: Create the package
      run: dotnet pack --configuration Release /p:AssemblyVersion=${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }} /p:Version=${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }} MauiKeyboardEffects/MauiKeyboardEffects.csproj
    - name: Publish the package to NuGet
      run: dotnet nuget push MauiKeyboardEffects/bin/Release/*.nupkg --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json
      env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
